### ISSUE TITLE
Function 'lua_call' not found

### ISSUE THREAD

**Issue by Micka33** [jmettraux/rufus-lua#33]
```shell
/Users/mickael/.rvm/gems/ruby-2.2.2/gems/ffi-1.9.10/lib/ffi/library.rb:261:in `attach_function': Function 'lua_call' not found in [/usr/local/lib/liblua.5.3.1.dylib] (FFI::NotFoundError)
	from /Users/mickael/.rvm/gems/ruby-2.2.2/gems/rufus-lua-1.1.2/lib/rufus/lua/lib.rb:84:in `<module:Lib>'
	from /Users/mickael/.rvm/gems/ruby-2.2.2/gems/rufus-lua-1.1.2/lib/rufus/lua/lib.rb:32:in `<module:Lua>'
	from /Users/mickael/.rvm/gems/ruby-2.2.2/gems/rufus-lua-1.1.2/lib/rufus/lua/lib.rb:30:in `<module:Rufus>'
	from /Users/mickael/.rvm/gems/ruby-2.2.2/gems/rufus-lua-1.1.2/lib/rufus/lua/lib.rb:29:in `<top (required)>'
	from /Users/mickael/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/mickael/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/mickael/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/mickael/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/mickael/.rvm/gems/ruby-2.2.2/gems/rufus-lua-1.1.2/lib/rufus/lua.rb:27:in `<top (required)>'
	from /Users/mickael/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/mickael/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/mickael/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/mickael/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/mickael/.rvm/gems/ruby-2.2.2/gems/rufus-lua-1.1.2/lib/rufus-lua.rb:2:in `<top (required)>'
	from /Users/mickael/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
	from /Users/mickael/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/mickael/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
	from /Users/mickael/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/mickael/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
	from /Users/mickael/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
	from /Users/mickael/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'

```

This error happens when adding `gem 'rufus-lua'`to my Gemfile.
```ruby
Lua 5.3.1  Copyright (C) 1994-2015 Lua.org, PUC-Rio
ruby '2.2.2'
gem 'rails', '4.2.1'
gem 'rufus-lua'
```

**Comment by Micka33** [comment]
Does not happen with Lua 5.1
```
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
```

**Comment by jmettraux** [comment]
Hello,

rufus-lua is Lua 5.1.x only, as stated on top of the README: https://github.com/jmettraux/rufus-lua/blob/master/README.md

Best regards.

**Comment by Micka33** [comment]
Ah! It didn't catch my eyes! My bad.  
This is not required for me anyway. Thx for your quick answer.
